"""add radio and lora fields

Revision ID: 4c23634e946a
Revises: e407db047c09
Create Date: 2026-04-04 21:01:07.622563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c23634e946a'
down_revision = 'e407db047c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_rssi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('snr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('channel_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gateway_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coding_rate', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('consumed_airtime', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.drop_column('consumed_airtime')
        batch_op.drop_column('coding_rate')
        batch_op.drop_column('gateway_count')
        batch_op.drop_column('channel_index')
        batch_op.drop_column('snr')
        batch_op.drop_column('channel_rssi')

    # ### end Alembic commands ###
