"""add fetch tracking to datasources

Revision ID: 7de9b3d160d8
Revises: e711d40b11a3
Create Date: 2026-04-06 11:19:18.077974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de9b3d160d8'
down_revision = 'e711d40b11a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_fetch_status', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('state')
        batch_op.drop_column('address')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.drop_column('last_fetch_status')
        batch_op.drop_column('last_fetched_at')

    # ### end Alembic commands ###
