"""fix ownership

Revision ID: 92710b6d7315
Revises: 7de9b3d160d8
Create Date: 2026-04-06 11:26:19.822852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92710b6d7315'
down_revision = '7de9b3d160d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datasource_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_uplink_messages_datasource_id'), ['datasource_id'], unique=False)
        batch_op.create_foreign_key(None, 'datasources', ['datasource_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_uplink_messages_datasource_id'))
        batch_op.drop_column('datasource_id')

    # ### end Alembic commands ###
