"""empty message

Revision ID: e407db047c09
Revises: 
Create Date: 2026-04-04 20:14:18.085571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e407db047c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uplink_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('f_cnt', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('spreading_factor', sa.Integer(), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('positioning_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'received_at', name='uq_device_received')
    )
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uplink_messages_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uplink_messages_received_at'), ['received_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('datasources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('bearer_token', sa.String(length=500), nullable=False),
    sa.Column('time_window', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasources')
    op.drop_table('users')
    with op.batch_alter_table('uplink_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uplink_messages_received_at'))
        batch_op.drop_index(batch_op.f('ix_uplink_messages_device_id'))

    op.drop_table('uplink_messages')
    # ### end Alembic commands ###
