"""enable or disable datasources

Revision ID: e711d40b11a3
Revises: 4c23634e946a
Create Date: 2026-04-04 22:48:09.357416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e711d40b11a3'
down_revision = '4c23634e946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
